/*
 * Copyright (c) 2025 BrainMateApp
 * All rights reserved.
 */
package com.github.aziznrrn.brainmate.forms;

import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import com.github.aziznrrn.brainmate.model.Contact;
import com.github.aziznrrn.brainmate.service.ContactService;
import com.github.aziznrrn.brainmate.util.ExportUtil;

/**
 * @author BMPC2024-8
 */
public class KontakFrame extends JFrame {
  public KontakFrame() {
    initComponents();
    loadAll();
  }

  private void loadAll() {
    DefaultTableModel m = (DefaultTableModel) tblKontak.getModel();
    m.setRowCount(0);
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    for (Contact c : ContactService.getAll()) {
      m.addRow(new Object[] {c.getId(), c.getCustomerId(), df.format(c.getDate()), c.getDetail()});
    }
  }

  private void loadSearch() {
    DefaultTableModel m = (DefaultTableModel) tblKontak.getModel();
    m.setRowCount(0);
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    for (Contact c : ContactService.search(0, txtSearch.getText().trim())) {
      m.addRow(new Object[] {c.getId(), c.getCustomerId(), df.format(c.getDate()), c.getDetail()});
    }
  }

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
    loadSearch();
  }

  private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
    txtSearch.setText("");
    loadAll();
  }

  private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {
    ExportUtil.exportTableToCSV(tblKontak, (JFrame) SwingUtilities.getWindowAncestor(this));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtSearch = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblKontak = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    btnTambah = new javax.swing.JButton();
    btnUbah = new javax.swing.JButton();
    btnHapus = new javax.swing.JButton();
    btnRefresh = new javax.swing.JButton();
    btnTutup = new javax.swing.JButton();

    jLabel1.setText("Cari:");

    btnSearch.setText("Cari");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jLabel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        36,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txtSearch,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        270,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(
                                        txtSearch,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                            .addComponent(jLabel1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    tblKontak.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
            },
            new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
    jScrollPane1.setViewportView(tblKontak);

    btnTambah.setText("Tambah");
    btnTambah.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTambahActionPerformed(evt);
          }
        });

    btnUbah.setText("Ubah");

    btnHapus.setText("Hapus");

    btnRefresh.setText("Refresh");

    btnTutup.setText("Tutup");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnTambah)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnUbah)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnHapus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnRefresh)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnTutup)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnTutup)
                            .addComponent(btnRefresh)
                            .addComponent(btnHapus)
                            .addComponent(btnUbah)
                            .addComponent(btnTambah))
                    .addContainerGap(17, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jPanel1,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                401,
                                                Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        285,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnTambahActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnTambahActionPerformed
    // TODO add your handling code here:
    try {
      int cid = Integer.parseInt(JOptionPane.showInputDialog(this, "Cust ID:"));
      String s = JOptionPane.showInputDialog(this, "Tanggal (yyyy-MM-dd):");
      Date date = new SimpleDateFormat("yyyy-MM-dd").parse(s);
      String d = JOptionPane.showInputDialog(this, "Detail:");
      ContactService.add(new Contact(0, cid, date, d));
      loadAll();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Format salah");
    }
  } // GEN-LAST:event_btnTambahActionPerformed

  private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {
    int sel = tblKontak.getSelectedRow();
    if (sel < 0) return;
    try {
      DefaultTableModel m = (DefaultTableModel) tblKontak.getModel();
      int id = (int) m.getValueAt(sel, 0);
      int cid =
          Integer.parseInt(JOptionPane.showInputDialog(this, "Cust ID:", m.getValueAt(sel, 1)));
      String s = JOptionPane.showInputDialog(this, "Tanggal (yyyy-MM-dd):", m.getValueAt(sel, 2));
      Date date = new SimpleDateFormat("yyyy-MM-dd").parse(s);
      String d = JOptionPane.showInputDialog(this, "Detail:", m.getValueAt(sel, 3));
      ContactService.update(new Contact(id, cid, date, d));
      loadAll();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Error");
    }
  }

  private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {
    int sel = tblKontak.getSelectedRow();
    if (sel < 0) return;
    if (JOptionPane.showConfirmDialog(
            this, "Hapus kontak ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION)
        == JOptionPane.YES_OPTION) {
      DefaultTableModel m = (DefaultTableModel) tblKontak.getModel();
      ContactService.delete((int) m.getValueAt(sel, 0));
      loadAll();
    }
  }

  private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {
    dispose();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHapus;
  private javax.swing.JButton btnRefresh;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnTambah;
  private javax.swing.JButton btnTutup;
  private javax.swing.JButton btnUbah;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblKontak;
  private javax.swing.JTextField txtSearch;
  // End of variables declaration//GEN-END:variables
}
