/*
 * Copyright (c) 2025 BrainMateApp
 * All rights reserved.
 */
package com.github.aziznrrn.brainmate.forms;

import java.awt.GridLayout;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import com.github.aziznrrn.brainmate.model.Product;
import com.github.aziznrrn.brainmate.service.ProductService;

/**
 * @author BMPC2024-8
 */
public class ProdukFrame extends JFrame {

  public ProdukFrame() {
    initComponents();
    btnSearch.addActionListener(e -> btnSearchActionPerformed(e));
    btnUbah.addActionListener(e -> btnUbahActionPerformed(e));
    btnHapus.addActionListener(e -> btnHapusActionPerformed(e));
    btnRefresh.addActionListener(e -> btnRefreshActionPerformed(e));
    btnTutup.addActionListener(e -> btnTutupActionPerformed(e));

    String[] columnNames = {"ID", "No", "Name", "Price", "Stock"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    tblProduk.setModel(model);
    tblProduk.getColumnModel().getColumn(0).setMinWidth(0);
    tblProduk.getColumnModel().getColumn(0).setMaxWidth(0);

    loadAll();
  }

  private void loadAll() {
    DefaultTableModel m = (DefaultTableModel) tblProduk.getModel();
    m.setRowCount(0);
    String kw = txtSearch.getText().trim();
    int index = 1;
    for (Product p : ProductService.search(kw)) {
      m.addRow(
          new Object[] {
            p.getId(), index++, p.getName(), p.getPrice(), p.getStock(),
          });
    }
  }

  private void loadSearch() {
    DefaultTableModel m = (DefaultTableModel) tblProduk.getModel();
    m.setRowCount(0);
    int index = 1;
    for (Product p : ProductService.getAll()) {
      m.addRow(
          new Object[] {
            p.getId(), index++, p.getName(), p.getPrice(), p.getStock(),
          });
    }
  }

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
    loadSearch();
  }

  private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
    txtSearch.setText("");
    loadAll();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtSearch = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblProduk = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    btnTambah = new javax.swing.JButton();
    btnUbah = new javax.swing.JButton();
    btnHapus = new javax.swing.JButton();
    btnRefresh = new javax.swing.JButton();
    btnTutup = new javax.swing.JButton();

    jLabel1.setText("Cari:");

    btnSearch.setText("Cari");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jLabel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        36,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txtSearch,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        270,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(
                                        txtSearch,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                            .addComponent(jLabel1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    tblProduk.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
            },
            new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
    jScrollPane1.setViewportView(tblProduk);

    btnTambah.setText("Tambah");
    btnTambah.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTambahActionPerformed(evt);
          }
        });

    btnUbah.setText("Ubah");

    btnHapus.setText("Hapus");

    btnRefresh.setText("Refresh");

    btnTutup.setText("Tutup");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnTambah)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnUbah)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnHapus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnRefresh)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnTutup)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnTutup)
                            .addComponent(btnRefresh)
                            .addComponent(btnHapus)
                            .addComponent(btnUbah)
                            .addComponent(btnTambah))
                    .addContainerGap(17, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jPanel1,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                401,
                                                Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        285,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnTambahActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnTambahActionPerformed
    // Form input components
    JTextField nameField = new JTextField(20);
    JTextField priceField = new JTextField(20);
    JTextField stockField = new JTextField(20);

    // Layout panel
    JPanel panel = new JPanel(new GridLayout(0, 1));
    panel.add(new JLabel("Name:"));
    panel.add(nameField);
    panel.add(new JLabel("Price:"));
    panel.add(priceField);
    panel.add(new JLabel("Stock:"));
    panel.add(stockField);

    // Show dialog
    int result =
        JOptionPane.showConfirmDialog(
            this, panel, "Add Product", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (result == JOptionPane.OK_OPTION) {
      String name = nameField.getText().trim();
      int price = Integer.parseInt(priceField.getText());
      int stock = Integer.parseInt(stockField.getText());

      if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Name is required.");
        return;
      }

      ProductService.add(new Product(0, name, price, stock));
      loadAll();
    }
  } // GEN-LAST:event_btnTambahActionPerformed

  private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {
    int sel = tblProduk.getSelectedRow();
    if (sel < 0) {
      JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu.");
      return;
    }

    DefaultTableModel m = (DefaultTableModel) tblProduk.getModel();

    int index = 0;
    int rowIdx = sel;
    for (Product c : ProductService.getAll()) {
      if (index == rowIdx) {
        // Form input components
        JTextField nameField = new JTextField(20);
        JTextField priceField = new JTextField(20);
        JTextField stockField = new JTextField(20);

        // Layout panel
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Name:"));
        panel.add(nameField);
        panel.add(new JLabel("Price:"));
        panel.add(priceField);
        panel.add(new JLabel("Stock:"));
        panel.add(stockField);

        // Show dialog
        int result =
            JOptionPane.showConfirmDialog(
                this,
                panel,
                "Add Product",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
          String name = nameField.getText().trim();
          int price = Integer.parseInt(priceField.getText());
          int stock = Integer.parseInt(stockField.getText());

          if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.");
            return;
          }

          ProductService.update(new Product(0, name, price, stock));
          loadAll();
        }
        break;
      }
      index++;
    }
  }

  private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {
    int sel = tblProduk.getSelectedRow();
    if (sel < 0) return;
    if (JOptionPane.showConfirmDialog(
            this, "Hapus pelanggan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION)
        == JOptionPane.YES_OPTION) {
      DefaultTableModel m = (DefaultTableModel) tblProduk.getModel();
      ProductService.delete((int) m.getValueAt(sel, 0));
      loadAll();
    }
  }

  private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {
    dispose();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHapus;
  private javax.swing.JButton btnRefresh;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnTambah;
  private javax.swing.JButton btnTutup;
  private javax.swing.JButton btnUbah;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblProduk;
  private javax.swing.JTextField txtSearch;
  // End of variables declaration//GEN-END:variables
}
