/*
 * Copyright (c) 2025 BrainMateApp
 * All rights reserved.
 */
package com.github.brainmate.BrainMateApp.forms;

import java.awt.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author BMPC2024-8
 */
public class ManajemenPenggunaFrame extends JFrame {

  public ManajemenPenggunaFrame() {
    super();
    initComponents();
    setupTable();
    setupEventHandlers();
  }

  private void setupTable() {
    String[] columnNames = {"ID", "Username", "Role", "Status"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    jTable1.setModel(model);
    jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
  }

  private void setupEventHandlers() {
    btnTambahUser.addActionListener(e -> btnTambahUserActionPerformed(e));
    btnUbahUser.addActionListener(e -> btnUbahUserActionPerformed(e));
    btnHapusUser.addActionListener(e -> btnHapusUserActionPerformed(e));
    btnResetPwd.addActionListener(e -> btnResetPwdActionPerformed(e));
    btnTutup.addActionListener(e -> btnTutupActionPerformed(e));
  }

  private void btnTambahUserActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: Implement add user functionality
  }

  private void btnUbahUserActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: Implement edit user functionality
  }

  private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: Implement delete user functionality
  }

  private void btnResetPwdActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: Implement reset password functionality
  }

  private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {
    dispose();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Manajemen Pengguna");

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    btnTambahUser = new javax.swing.JButton();
    btnUbahUser = new javax.swing.JButton();
    btnHapusUser = new javax.swing.JButton();
    btnResetPwd = new javax.swing.JButton();
    btnTutup = new javax.swing.JButton();

    jTable1.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
            },
            new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
    jScrollPane1.setViewportView(jTable1);

    btnTambahUser.setText("Tambah User");
    btnUbahUser.setText("Ubah User");
    btnHapusUser.setText("Hapus User");
    btnResetPwd.setText("Reset Password");
    btnTutup.setText("Tutup");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jScrollPane1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                600,
                                Short.MAX_VALUE)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(btnTambahUser)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUbahUser)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnHapusUser)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnResetPwd)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(btnTutup)))
                    .addContainerGap()));

    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambahUser)
                            .addComponent(btnUbahUser)
                            .addComponent(btnHapusUser)
                            .addComponent(btnResetPwd)
                            .addComponent(btnTutup))
                    .addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHapusUser;
  private javax.swing.JButton btnResetPwd;
  private javax.swing.JButton btnTambahUser;
  private javax.swing.JButton btnTutup;
  private javax.swing.JButton btnUbahUser;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
