/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainmateapp;

import brainmateapp.forms.*;
import java.beans.PropertyVetoException;
import javax.swing.*;

/**
 *
 * @author BMPC2024-8
 */
public class BrainMateGUI extends JFrame {
    private final JDesktopPane desktopPane = new JDesktopPane();

    public BrainMateGUI() {
        super("BrainMate CRM");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);

        setContentPane(desktopPane);
        createMenuBar();
    }
    
    private void createMenuBar() {
        JMenuBar mb = new JMenuBar();

        // --- Form Master ---
        JMenu mMaster = new JMenu("Form Master");
        JMenuItem miPelanggan = new JMenuItem("Pelanggan");
        JMenuItem miProduk     = new JMenuItem("Produk/Layanan");
        JMenuItem miTimSales   = new JMenuItem("Tim Sales/Marketing");
        JMenuItem miKontak     = new JMenuItem("Kontak & Komunikasi");
        miPelanggan.addActionListener(e -> openFrame(new PelangganFrame()));
        miProduk   .addActionListener(e -> openFrame(new ProdukFrame()));
        miTimSales .addActionListener(e -> openFrame(new MarketingFrame()));
        miKontak   .addActionListener(e -> openFrame(new KontakFrame()));
        mMaster.add(miPelanggan);
        mMaster.add(miProduk);
        mMaster.add(miTimSales);
        mMaster.add(miKontak);
        mb.add(mMaster);

        // --- Form Transaksi ---
        JMenu mTrans = new JMenu("Form Transaksi");
        JMenuItem miPemesanan = new JMenuItem("Pemesanan / Penjualan");
        JMenuItem miFeedback  = new JMenuItem("Feedback & Keluhan");
        miPemesanan.addActionListener(e -> openFrame(new PemesananFrame()));
        miFeedback .addActionListener(e -> openFrame(new FeedbackFrame()));
        mTrans.add(miPemesanan);
        mTrans.add(miFeedback);
        mb.add(mTrans);

        // --- Laporan ---
        JMenu mLap = new JMenu("Laporan");
        JMenuItem miLapPelanggan = new JMenuItem("Lap. Pelanggan Aktif");
        JMenuItem miLapPenjualan = new JMenuItem("Lap. Penjualan / Periode");
        JMenuItem miLapKinerja   = new JMenuItem("Lap. Kinerja Sales");
        JMenuItem miLapFeedback  = new JMenuItem("Lap. Feedback & Keluhan");
        miLapPelanggan.addActionListener(e -> openFrame(new LapPelangganFrame()));
        miLapPenjualan.addActionListener(e -> openFrame(new LapPenjualanFrame()));
        miLapKinerja  .addActionListener(e -> openFrame(new LapKinerjaFrame()));
        miLapFeedback .addActionListener(e -> openFrame(new LapFeedbackFrame()));
        mLap.add(miLapPelanggan);
        mLap.add(miLapPenjualan);
        mLap.add(miLapKinerja);
        mLap.add(miLapFeedback);
        mb.add(mLap);

        // --- Pengaturan ---
        JMenu mSet = new JMenu("Pengaturan");
        JMenuItem miUserMgmt = new JMenuItem("Manajemen Pengguna");
        JMenuItem miBackup   = new JMenuItem("Backup Data");
        JMenuItem miAnalisis = new JMenuItem("Analisis Bisnis");
        miUserMgmt.addActionListener(e -> openFrame(new ManajemenPenggunaFrame()));
        miBackup  .addActionListener(e -> openFrame(new BackupDataFrame()));
        miAnalisis.addActionListener(e -> openFrame(new AnalisisBisnisFrame()));
        mSet.add(miUserMgmt);
        mSet.add(miBackup);
        mSet.add(miAnalisis);
        mb.add(mSet);

        setJMenuBar(mb);
    }
    
    private void openFrame(JInternalFrame f) {
        desktopPane.add(f);
        f.setVisible(true);
        try { f.setSelected(true); }
        catch(PropertyVetoException ex) { ex.printStackTrace(); }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new BrainMateGUI().setVisible(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        miPelanggan = new javax.swing.JMenuItem();
        miProduk = new javax.swing.JMenuItem();
        miMarketing = new javax.swing.JMenuItem();
        miKontak = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miPemesanan = new javax.swing.JMenuItem();
        miFeedback = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miLapPelanggan = new javax.swing.JMenuItem();
        miLapPenjualan = new javax.swing.JMenuItem();
        miLapKinerja = new javax.swing.JMenuItem();
        miLapFeedback = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        miUserMgmt = new javax.swing.JMenuItem();
        miBackup = new javax.swing.JMenuItem();
        miAnalisis = new javax.swing.JMenuItem();

        jMenu3.setText("Form Master");

        jMenu4.setText("Form Transaksi");

        jMenu5.setText("Laporan");

        jMenu6.setText("Pengaturan");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu7.setText("Form Master");

        miPelanggan.setText("Pelanggan");
        miPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPelangganActionPerformed(evt);
            }
        });
        jMenu7.add(miPelanggan);

        miProduk.setText("Produk/Layanan");
        jMenu7.add(miProduk);

        miMarketing.setText("Tim Sales/Marketing");
        jMenu7.add(miMarketing);

        miKontak.setText("Kontak & Komunikasi");
        jMenu7.add(miKontak);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Form Transaksi");

        miPemesanan.setText("Pemesanan / Penjualan");
        jMenu8.add(miPemesanan);

        miFeedback.setText("Feedback & Keluhan");
        jMenu8.add(miFeedback);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Laporan");

        miLapPelanggan.setText("Laporan Pelanggan Aktif");
        jMenu9.add(miLapPelanggan);

        miLapPenjualan.setText("Laporan Penjualan per Periode");
        jMenu9.add(miLapPenjualan);

        miLapKinerja.setText("Laporan Kinerja Sales");
        jMenu9.add(miLapKinerja);

        miLapFeedback.setText("Laporan Feedback & Keluhan");
        jMenu9.add(miLapFeedback);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Pengaturan");

        miUserMgmt.setText("Manajemen Pengguna");
        jMenu10.add(miUserMgmt);

        miBackup.setText("Backup Data");
        jMenu10.add(miBackup);

        miAnalisis.setText("Analisis Bisnis");
        miAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnalisisActionPerformed(evt);
            }
        });
        jMenu10.add(miAnalisis);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnalisisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAnalisisActionPerformed

    private void miPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPelangganActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAnalisis;
    private javax.swing.JMenuItem miBackup;
    private javax.swing.JMenuItem miFeedback;
    private javax.swing.JMenuItem miKontak;
    private javax.swing.JMenuItem miLapFeedback;
    private javax.swing.JMenuItem miLapKinerja;
    private javax.swing.JMenuItem miLapPelanggan;
    private javax.swing.JMenuItem miLapPenjualan;
    private javax.swing.JMenuItem miMarketing;
    private javax.swing.JMenuItem miPelanggan;
    private javax.swing.JMenuItem miPemesanan;
    private javax.swing.JMenuItem miProduk;
    private javax.swing.JMenuItem miUserMgmt;
    // End of variables declaration//GEN-END:variables
}
